databases:
  - name: trem_app_db
    plan: free
    databaseName: trem_app
    user: trem_admin

services:
  - type: web
    plan: free
    name: trem
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn trem.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: trem.settings
