# Generated by Django 5.0.7 on 2024-07-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trem_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
