# Generated by Django 5.0.7 on 2024-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trem_app', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(auto_created=True, editable=False, max_length=200, unique=True),
        ),
    ]
