# Generated by Django 5.0.7 on 2024-07-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trem_app', '0003_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
