# Generated by Django 5.0.7 on 2024-07-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trem_app', '0005_alter_note_slug_alter_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
    ]
