# Generated by Django 5.0.7 on 2024-08-29 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trem_app', '0006_remove_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trem_app.note'),
        ),
    ]
