# Generated by Django 5.0.7 on 2024-08-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trem_app', '0007_note_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='thread',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='note',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
